version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      astro:
        patterns: ['astro', '@astrojs/*']
        update-types: [minor, patch]
      fonts:
        patterns: ['@fontsource*/*']
        update-types: [minor, patch]
    commit-message:
      prefix: deps
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
